api:
  dashboard: true        # Enable Traefik web dashboard at :8080 (optional)

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false  # Services must explicitly enable Traefik via labels
    network: app-net         # Must match your Docker network name

certificatesResolvers:
  myresolver:
    acme:
      email: you@example.com
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

log:
  level: INFO

accessLog: {}
